### ISSUE TITLE
Feature Request: Allow artifacts to be uploaded under a different name than its original file name

### ISSUE THREAD

**Issue by wl2522** [neptune-ai/neptune-sacred#7] opened 2021-08-20 21:43 UTC
The legacy `NeptuneObserver` integration in `neptune-contrib` only looked at an artifact's file name when calling `ex.add_artifact()`. With the new `NeptuneObserver` in `neptune-sacred`, the `filename` and `name` parameters must be the same, since `artifact_event()` will attempt to upload a file that's located at `name` rather than `filename`. 

Previously, I would save a model artifact to my local drive, and then add it to Sacred with a date stamp prefix so that I can distinguish between different versions of the same model artifact. For example:

```
     ex.add_artifact(config['artifacts']['val_curves_fname'],
                     name=f"{DATE}_{config['artifacts']['val_curves_fname']}")
```

However, I'm not longer able to do this due to the change mentioned above (Neptune will try to upload a file named `f"{DATE}_{config['artifacts']['val_curves_fname']}"` but it won't work because that's the name of the copy of the file within the experiment logs saved by `FileStorageObserver`, not the original file name).

**Comment by Blaizzy** [comment] 2021-08-26 09:08
Hi @wl2522 

I'm Prince Canuma, a Data Scientist at Neptune.ai 

I have reproduced the issue and submited a ticket to the engineering,

And either I or they will reach out to you once it's solved!

Kind regards

**Comment by wl2522** [comment] 2021-09-29 19:30
Hi @Blaizzy! Could you please let me know if there have been any updates on this issue (or the others that I filed, especially #5)?

I'm currently preparing a model deployment to production with Docker and it would be great if the fixes for these bugs have been implemented rather than me needing to fork this repo to manually patch the fixes.

Thank you for your assistance!

**Comment by Blaizzy** [comment] 2021-09-30 09:40
Hi @wl2522 

Thanks for reaching out :) 

I submitted the ticket but as of now, there is still no update from the engineering team yet, 

I think your suggestion of forking is a better alternative. Would you mind proposing a solution and make a PR to the repo? 

If you can do that I will work my best to make sure your PR is reviewed and merged promptly by the engineering team!

And by the way, since you speak of Docker I want to let you know that I created a guide on how to use **Neptune with Docker** and it was released last week, check it out in our docs:

- https://docs.neptune.ai/how-to-guides/automation-pipelines/how-to-use-neptune-with-docker

**Comment by wl2522** [comment] 2021-10-01 06:44
Hi again @Blaizzy, I created PRs for all of the suggested feature requests/bug fixes that I described, aside from #6, which I think is an issue with the Neptune web interface itself (as I stated in that issue thread).

I hope these PRs are all okay (they're my first PRs for an open-source project!), but feel free to make/suggest edits as needed.

**Comment by Blaizzy** [comment] 2021-10-01 11:38
Hi, @wl2522 I got them, thank you very much! I also submitted them to the engineering team, they will be in touch with you soon as possible through the PRs you made.

**Closed as completed** 2021-10-01 15:08 UTC

**Comment by Raalsky** [comment] 2021-10-05 07:36
Hey @wl2522 @Blaizzy, I just want to let you know that the latest version of `neptune-sacred` was published on PyPI :wink:. It includes all of the PRs proposed by @wl2522. I really appreciate your efforts.

**Comment by Blaizzy** [comment] 2021-10-05 07:47
Great, thank you @wl2522 and @Raalsky!

**Comment by wl2522** [comment] 2021-10-05 20:39
Thank you for the quick turnaround with publishing version 0.9.7 (as well as your prompt feedback/PR approvals) @Raalsky 🙏 
I upgraded to this new version and confirmed that all of the issues that I reported have now been resolved 🎉
